/**
 * Maps a link written inside a repository document to what the browser can show for it.
 * Documents link to each other by repository-relative paths (`../../wiki/architecture.md`), so the target is resolved
 * against the folder of the document being read and then matched to a wiki page, a feature spec, an asset, or nothing.
 */
export type DocumentIndex = { documents: readonly { id: string; path: string }[]; features: readonly { id: string; path: string }[] };
export type ResolvedLink =
  | { kind: 'external'; href: string }
  | { kind: 'anchor'; href: string }
  /** An absolute in-app route such as `/features/S-x?tab=design`; documents generated by the browser itself use these. */
  | { kind: 'app'; href: string }
  | { kind: 'wiki'; documentId: string; path: string; hash: string }
  | { kind: 'feature'; featureId: string; tab: 'requirements' | 'design'; path: string; hash: string }
  | { kind: 'asset'; url: string; path: string }
  /** A store path with no matching page or feature in the loaded specs. */
  | { kind: 'missing'; path: string }
  /** A repository file the browser does not serve, such as `docs/development.md`. */
  | { kind: 'outside'; path: string };

const scheme = /^[a-z][a-z0-9+.-]*:/i;
export const wikiEntryPath = '.gitifact/wiki/README.md';

/** Joins `href` onto the folder of `from`, handling `.` and `..`; undefined when it would climb above the repository root. */
export function resolveRepositoryPath(from: string | undefined, href: string): string | undefined {
  let decoded = href;
  try { decoded = decodeURI(href); } catch { /* keep the raw text; a malformed escape is still a path */ }
  const segments = (from ?? '').split('/').slice(0, -1);
  for (const part of decoded.split('/')) {
    if (part === '' || part === '.') continue;
    if (part === '..') { if (!segments.length) return undefined; segments.pop(); continue; }
    segments.push(part);
  }
  return segments.join('/');
}

export function resolveDocumentLink(href: string, from: string | undefined, index: DocumentIndex): ResolvedLink {
  if (scheme.test(href) || href.startsWith('//')) return { kind: 'external', href };
  if (href.startsWith('#')) return { kind: 'anchor', href };
  if (href.startsWith('/')) return { kind: 'app', href };
  const hashAt = href.indexOf('#'); const hash = hashAt >= 0 ? href.slice(hashAt) : '';
  const bare = (hashAt >= 0 ? href.slice(0, hashAt) : href).split('?')[0]!;
  const path = resolveRepositoryPath(from, bare);
  if (path === undefined) return { kind: 'outside', path: href };
  if (/^\.gitifact\/wiki\/.+\.md$/.test(path)) {
    const page = index.documents.find(d => d.path === path);
    return page ? { kind: 'wiki', documentId: page.id, path, hash } : { kind: 'missing', path };
  }
  const spec = /^(\.gitifact\/spec\/[^/]+\/)(requirements|design)\.md$/.exec(path);
  if (spec) {
    const feature = index.features.find(f => f.path === spec[1] + 'requirements.md');
    return feature ? { kind: 'feature', featureId: feature.id, tab: spec[2] as 'requirements' | 'design', path, hash } : { kind: 'missing', path };
  }
  const asset = /^\.gitifact\/assets\/(.+)$/.exec(path);
  if (asset) return { kind: 'asset', url: '/api/v1/assets/' + asset[1]!.split('/').map(encodeURIComponent).join('/'), path };
  return { kind: 'outside', path };
}

/** The folder of a design file, which is where its relative source links start from. */
export const designPathOf = (featurePath: string) => featurePath.replace(/requirements\.md$/, 'design.md');
