/**
 * Maps a link written inside a repository document to what the browser can show for it.
 * Documents link to each other by repository-relative paths (`../../spec/posts/index.md`), so the target is resolved
 * against the folder of the document being read and then matched to a feature spec, an instruction, AGENTS.md, an asset, or nothing.
 * The browser does not show the wiki, so a wiki page is missing like any other store path it cannot open.
 */
type Located = { id: string; path: string; title?: string };
export type DocumentIndex = { features: readonly (Located & { requirements?: readonly Located[]; designs?: readonly Located[] })[]; instructions?: readonly Located[] };
export type ResolvedLink =
  | { kind: 'external'; href: string }
  | { kind: 'anchor'; href: string }
  /** An absolute in-app route such as `/features/S-x?tab=design`; documents generated by the browser itself use these. */
  | { kind: 'app'; href: string }
  | { kind: 'feature'; featureId: string; tab: 'requirements' | 'design'; path: string; hash: string }
  /** An instruction's index.md or one of the other files of its folder (`file`, relative to the folder). */
  | { kind: 'instruction'; instructionId: string; file: string | undefined; path: string; hash: string }
  /** AGENTS.md at the repository root, which the instructions page shows. */
  | { kind: 'agents'; path: string; hash: string }
  | { kind: 'asset'; url: string; path: string }
  /** A store path with no matching page or feature in the loaded specs. */
  | { kind: 'missing'; path: string }
  /** A repository file the browser does not serve, such as `docs/development.md`. */
  | { kind: 'outside'; path: string };

const scheme = /^[a-z][a-z0-9+.-]*:/i;

/** Joins `href` onto the folder of `from`, handling `.` and `..`; undefined when it would climb above the repository root. */
export function resolveRepositoryPath(from: string | undefined, href: string): string | undefined {
  let decoded = href;
  try { decoded = decodeURI(href); } catch { /* keep the raw text; a malformed escape is still a path */ }
  const segments = (from ?? '').split('/').slice(0, -1);
  for (const part of decoded.split('/')) {
    if (part === '' || part === '.') continue;
    if (part === '..') { if (!segments.length) return undefined; segments.pop(); continue; }
    segments.push(part);
  }
  return segments.join('/');
}

export function resolveDocumentLink(href: string, from: string | undefined, index: DocumentIndex): ResolvedLink {
  if (scheme.test(href) || href.startsWith('//')) return { kind: 'external', href };
  if (href.startsWith('#')) return { kind: 'anchor', href };
  if (href.startsWith('/')) return { kind: 'app', href };
  const hashAt = href.indexOf('#'); const hash = hashAt >= 0 ? href.slice(hashAt) : '';
  const bare = (hashAt >= 0 ? href.slice(0, hashAt) : href).split('?')[0]!;
  const path = resolveRepositoryPath(from, bare);
  if (path === undefined) return { kind: 'outside', path: href };
  // A feature's index.md opens the feature, whose introduction heads the requirements; a requirement or design file opens that document on its tab.
  const spec = /^(\.gitifact\/spec\/[^/]+\/)(?:index\.md|(requirements|design)\/[^/]+\.md)$/.exec(path);
  if (spec) {
    const feature = index.features.find(f => f.path === spec[1] + 'index.md');
    if (!feature) return { kind: 'missing', path };
    if (!spec[2]) return { kind: 'feature', featureId: feature.id, tab: 'requirements', path, hash };
    const tab = spec[2] as 'requirements' | 'design';
    const doc = (tab === 'requirements' ? feature.requirements : feature.designs)?.find(d => d.path === path);
    return doc ? { kind: 'feature', featureId: feature.id, tab, path, hash: hash || '#' + doc.id } : { kind: 'missing', path };
  }
  if (path === 'AGENTS.md') return { kind: 'agents', path, hash };
  const instruction = /^(\.gitifact\/instructions\/[^/]+)(?:\/(.*))?$/.exec(path);
  if (instruction) {
    const found = index.instructions?.find(k => k.path === instruction[1] + '/index.md');
    if (!found) return { kind: 'missing', path };
    const file = !instruction[2] || instruction[2] === 'index.md' ? undefined : instruction[2];
    return { kind: 'instruction', instructionId: found.id, file, path, hash };
  }
  const asset = /^\.gitifact\/assets\/(.+)$/.exec(path);
  if (asset) return { kind: 'asset', url: '/api/v1/assets/' + asset[1]!.split('/').map(encodeURIComponent).join('/'), path };
  return { kind: 'outside', path };
}

